### PR TITLE
Sanity Check

### PR DESCRIPTION
**Pull request by NamYehyun**
Add sanity check codes to `readGraph`.

### CODE REVIEW

**Comment by gmgu** [comment]
Great job. There are some comments.

1. loops can be checked while reading the graph from the file.

2. consider using Memory.getLLArray instead of new (graph.cpp, line 195, int32_t* tmp = new int32_t[numNode];)

3. parallel edge check can be done in O(E) time using an array C and a stack S of length |V| as follows: initially C[i]=0 for 0<=i<|V|; for each neighbor v of u in V(G), set C[v] = C[v] + 1 C[v] add v to S; if there exists v such that C[v] > 1, v appears more than once in the adjacency list of u; after scanning all neighbors of u, set C[v]=0 for each vertex in S, and clear S. 

4. We should avoid queue and vector in readGraphs because there are expensive data structures when we deal with large-scale graphs. I recommend to use Memory.getLLArray to get arrays and use them in place of std::queue and std::vector

**Comment by gmgu** [comment]
Checking the existence of parallel edges takes O(V^2) time since it initialize whole adj for every u in V(G).
You should use a stack that stores visited neighbors of u, and initialize adj[i] for vertices i in the stack at the end of the loop.
Then, it takes O(E) time to check parallel edges.

Also, I did not check the code about connectivity.
Perhaps some comments on the source code would be helpful for me (or other readers) to understand.

**Comment by NamYehyun** [comment]
I see. I modified the code as you suggested.
I check whether the graph is connected as follows:
1. Perform a BFS on the graph, starting from vertex 0. During traversal, mark all visited vertices.
2. If any vertex is not marked, then the graph is not connected. Otherwise, it is connected.

**Comment by gmgu** [comment]
Sorry for keep commenting.

1. Please follow our coding convention. (for example, avoid ++s_top)
2. Using functions to implement stack operations makes readers easy to read the code. 
However it may sacrifice the performance due to the function call overhead.

**Comment by gmgu** [comment]
Well done.

**Pull request merged**
